title: "Kuramoto Anna"
name: "倉本安奈"
url: "https://myporns.github.io"
description: "日本の元ロリータ系AV女優。神奈川県出身。"
fbi:
  title: "FBI WARNINGS"
  description: "Federal Law provides severe civil<br />and criminal penalties for the<br />unauthorized reproduction, distribution,<br />or exhibition of copyrighted motion pictures."
drive: "https://pan.baidu.com/s/1WQ5zHCihmcV1z46oZsHErg"
password: "997f"
copyright: "倉本安奈 • 2017-2018"
copyright_full: "Copyright &copy; 2017-2018 倉本安奈. All rights reserved."
author: "倉本安奈"
author_short: "Anna"
github: "https://github.com/MyPorns"
github_repo: "https://github.com/MyPorns/myporns.github.io"

exclude: ['Gemfile.lock', 'Gemfile', 'Rakefile']

highlighter: rouge
#pygments
markdown: kramdown
permalink: /posts/:title/
blog_perma: "https://myporns.github.io/posts"
# Plugins
plugins: [jekyll-paginate,liquid]
# Gems
gems: [jekyll-paginate,liquid]
paginate: 15
paginate_path: "/posts/page/:num"
